# Generated by Django 6.0 on 2026-01-07 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', max_length=255)),
                ('pgn', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('finished', 'Finished')], default='waiting', max_length=10)),
                ('cadence', models.CharField(choices=[('1+0', '1+0'), ('2+1', '2+1'), ('3+0', '3+0'), ('5+0', '5+0')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('black_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_black', to=settings.AUTH_USER_MODEL)),
                ('white_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_white', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
